config/routes.rb
Amua::Application.routes.draw do
  root to: 'users#index'

  get 'users/login'
  get 'users/register'
  get 'id:id' => 'users#show', as: 'show_user'
  get 'search' => 'engine#search', as: 'search'
  get 'haml_to_html' => 'test#hth', as: 'hth'
  get '/test/get_last_user_fullname'
  # get '/users/:id' => redirect('/')

  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users
  resources :posts
  resources :comments

  resources :posts, :comments, only: [] do
    member do
      match :like, via: [:get, :post]
      match :unlike, via: [:get, :post]
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validate :first_name, presenсe: true
  validate :last_name, presenсe: true
  has_many :posts
  has_many :owned_posts, class_name: 'Post', foreign_key: 'owner_id'

  def fullname
    if first_name.present? and last_name.present?
      "#{first_name} #{last_name}, id = #{id}"
    else
      email
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def new
    @user = User.new
  end

  def create
    @user = User.new(sign_up_params)
    @candidate = "#{@user.first_name} #{@user.last_name} #{@user.id}".parameterize
    if @user.save
      sign_up(:user, @user)
      redirect_to @user
    else
      render :new, alert: 'Cannot create profile. Please try again'
    end
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete("password")
      params[:user].delete("password_confirmation")
    end

    @user = User.find(current_user.id)
    if @user.update_attributes(user_params)
      set_flash_message :notice, :updated
      sign_in @user, :bypass => true
      redirect_to after_update_path_for(@user)
    else
      render "edit"
    end
  end

  def edit
    super
  end


  def show
    super
  end

  def sign_up
    redirect_to users_register_path
  end

  def destroy
    @user = User.find(current_user.id)
    @user.destroy
    redirect_to root_path, notice: "You successfully removed your profile"

    @user.sent_messages.each do |message|
      message.destroy
    end

    @user.recieved_messages.each do |message|
      message.destroy
    end

    @user.relationships.each do |relationship|
      relationship.destroy
    end

    @user.reverse_relationships.each do |relationship|
      relationship.destroy
    end

    @user.user_articles.each do |article|
      article.destroy
    end

    @user.comments.each do |comment|
      comment.destroy
    end

    @user.groups.each do |group|
      group.destroy
    end

  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :avatar, :avatar_cache, :last_name, :age, :sex, :hometown, :email, :password, :pasword_confirmation) }
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :avatar, :avatar_cache, :born_date, :sex, :hometown, :email, :password, :pasword_confirmation, :paused, :about, :prefer_lang, :uid)
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < ApplicationController
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def new
  end

  def create
    @user = User.find(user_params)
    sign_in(@user)
    redirect_to @user
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :avatar, :avatar_cache, :last_name, :age, :sex, :hometown, :email, :password, :pasword_confirmation) }
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :avatar, :avatar_cache, :born_date, :sex, :hometown, :email, :password, :pasword_confirmation, :paused, :about, :prefer_lang, :uid)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: :show

  def index
    @users = User.order(created_at: :desc)
  end

  def login

  end

  def sign_up
    redirect_to users_register_path
  end

  def update
    @user = User.find(current_user.id)
    if @user.update_attributes(user_params)
      redirect_to @user
    end
  end

  def register

  end

  def show
    @posts = @user.owned_posts.order(created_at: :desc)
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

end

app/views/users/_user.html.haml
%li.media.post{ id: "user_#{user.id}" }
  = link_to user, class: 'pull-left' do
    = image_tag 'udef.png'
  .media-body
    %h4.media-heading
      = user.fullname
    = user.email

app/views/users/index.html.haml
%h1.text-center.text-success Users list
.row
  .col-md-8.col-md-offset-2
    %ul.media-list
      - @users.each do |user|
        %li.media
          = link_to show_user_path(user), class: 'pull-left' do
            = image_tag 'udef.png'
          .media-body
            %h4.media-heading= user.fullname
            = user.email

app/views/users/login.html.haml
.row
  .col-md-3
    = form_tag session_path(:user) do
      .input-group.input-group-lg
        %span.input-group-addon @
        = text_field_tag 'user[email]', nil, class: 'form-control'
      %br
      .input-group.input-group-lg
        %span.input-group-addon ***
        = password_field_tag 'user[password]', nil, class: 'form-control'
      %br
      .text-right
        %button.btn.btn-default.btn-lg Sign in
    = check_box_tag 'user[remember_me]'
    = label_tag 'user[remember_me]', 'Remember me'
    %br
    = link_to "Don't have an account?", new_user_registration_path
  .col-md-9
    .jumbotron
      %h1 am.ua - social
      %p You can register or login for free!
      %p.text-muted= link_to 'Wiki', '#'

app/views/users/register.html.haml
.col-md-3
  = form_tag registration_path(:user) do
    %br
    .input-group.input-group-lg
      %span.input-group-addon ***
      = text_field_tag 'user[first_name]', nil, class: 'form-control', placeholder: 'first name'
    %br
    .input-group.input-group-lg
      %span.input-group-addon ***
      = text_field_tag 'user[last_name]', nil, class: 'form-control', placeholder: 'last name'
    %br
    .input-group.input-group-lg
      %span.input-group-addon @
      = text_field_tag 'user[email]', nil, class: 'form-control', placeholder: 'email'
    %br
    .input-group.input-group-lg
      %span.input-group-addon ***
      = password_field_tag 'user[password]', nil, class: 'form-control', placeholder: 'password'
    %br
    .input-group.input-group-lg
      %span.input-group-addon ***
      = password_field_tag 'user[password_confirmation]', nil, class: 'form-control', placeholder: 'confirm password'
    %br
    .text-right
      %button.btn.btn-default.btn-lg Sign up
  = link_to "Already have an account?", new_user_session_path
.col-md-9
  .jumbotron
    %h1 am.ua - social
    %p You can register or login for free!
    %p.text-muted= link_to 'Wiki', '#'

app/views/users/show.html.haml
.row
  .col-md-4
    .well.text-center
      = image_tag 'udef.png'
      %h3= @user.fullname
      %hr
      - if user_signed_in? and current_user == @user
        = link_to edit_registration_path(current_user), class: 'btn btn-default' do
          %i.fa.fa-pencil &nbsp;Edit information
  .col-md-8
    .well
      = render 'posts/form_inputs'
    %ul.media-list.User
      - @posts.each do |post|
        = render 'posts/post', post: post